### ISSUE TITLE
after sending 5 transactions, all nodes get disconnect

### ISSUE THREAD

**Issue by istabraq-iot** [kashishkhullar/pbft#1]
Hi 

I have run 3 nodes and after sending 5 transactions the node get disconnect, how could solve this ?
![Screenshot from 2020-05-13 08-41-03](https://user-images.githubusercontent.com/60552945/81834298-6d78b580-9549-11ea-94aa-cc7c45516058.png)
![Screenshot from 2020-05-13 08-41-11](https://user-images.githubusercontent.com/60552945/81834308-6f427900-9549-11ea-9813-17156994035d.png)
![Screenshot from 2020-05-13 08-41-13](https://user-images.githubusercontent.com/60552945/81834312-6fdb0f80-9549-11ea-8456-bed5e652666a.png)
![Screenshot from 2020-05-13 08-41-28](https://user-images.githubusercontent.com/60552945/81834314-7073a600-9549-11ea-96f2-789f8bce6573.png)

**Comment by istabraq-iot** [comment]
@kashishkhullar

**Comment by kashishkhullar** [comment]
Hi @istabraq-iot 
Thanks for letting me know
There was a minor bug in my code, which I don't how I missed. So I have committed a fix.
